Tombstones.UI.Web/Tombstones.UI.Web/Controllers/FileManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace Tombstones.UI.Web.Controllers
{
    public class FileManagerController : BaseController
    {

        //
        // GET: /FileManager/

        public static string IndexLinkPath = "/filemanager/";

        public ActionResult Index()
        {
#if DEBUG
            if (TempData["newFile"] != null)
            {
                ViewBag.NewFile = TempData["newFile"];
            }

            if (TempData["RecordsAdded"] != null && TempData["ImportTimeSpan"] != null)
            {
                ViewBag.RecordsAdded = (int)TempData["RecordsAdded"];
                ViewBag.ImportTimeSpan = (TimeSpan)TempData["ImportTimeSpan"];

                ViewBag.SuccessMessage = string.Format("Imported '{0}' records in {1:0.00} seconds", ViewBag.RecordsAdded, ((TimeSpan)ViewBag.ImportTimeSpan).TotalSeconds);
            }

            var uploadedFiles = RavenSession.Query<Models.UploadedFile>()
                .OrderBy(f => f.FileName);

            var model = ViewModels.FileManagerIndex.Create(Server.MapPath("~/App_Data/uploads/"));
            foreach (var dbFile in uploadedFiles)
            {
                model.UploadedFiles.Add(dbFile);
            }

            return View(model);
#else
            return RedirectToRoute("Default");
#endif
        }

        public static string UploadLinkPath = "/filemanager/upload/";
        [HttpGet]
        public ActionResult Upload()
        {
#if DEBUG
            var model = new ViewModels.FileUpload();

            return View(model);
#else
            return RedirectToRoute("Default");
#endif
        }

        [HttpPost]
        public ActionResult Upload(ViewModels.FileUpload model, FormCollection formdata)
        {
#if DEBUG
            model.FileBeingUploaded = new Models.UploadedFile
            {
                Category = model.SelectedFileCategory,
                UploadedAt = DateTime.Now
            };

            HttpPostedFileBase hpf = Request.Files["uploadedFile"] as HttpPostedFileBase;
            if (hpf == null || hpf.ContentLength == 0)
            {
                ViewBag.ErrorMessage = "That file contained no data...";
                return ViewBag(model);
            }

            string savedFilePath = Path.Combine(
               AppDomain.CurrentDomain.BaseDirectory, "App_Data",
                "uploads",
                model.SelectedFileCategory.ToLower());

            string savedFileName = Path.Combine(savedFilePath,
            hpf.FileName);

            if (System.IO.File.Exists(savedFileName))
            {
                ViewBag.ErrorMessage = string.Format("That filename already exists: {0}",
                    savedFileName.Substring(savedFileName.IndexOf("App_Data") + "App_Data".Length + 1));
                return View(model);
            }
            try
            {
                hpf.SaveAs(savedFileName);

            }
            catch (Exception)
            {
                System.IO.Directory.CreateDirectory(savedFilePath);
                hpf.SaveAs(savedFileName);
            }
            model.FileBeingUploaded.FullPath = savedFileName;
            model.FileBeingUploaded.FileName = hpf.FileName;

            RavenSession.Store(model.FileBeingUploaded);
            if (TempData.ContainsKey("newFile"))
                TempData["newFile"] = model.FileBeingUploaded;
            else
                TempData.Add("newFile", model.FileBeingUploaded);

            return RedirectToAction("index");
#else
            return RedirectToRoute("Default");
#endif
        }

        public static string ImportLinkPath = "/filemanager/import/";
        [HttpGet]
        public ActionResult Import(string id)
        {
#if DEBUG
            var uploadId = id;
            ViewModels.FileManagerImport model = null;

            Models.UploadedFile uploadFile = RavenSession.Load<Models.UploadedFile>(uploadId);

            if (uploadFile != null && !uploadFile.ImportedAt.HasValue)
            {
                model = ViewModels.FileManagerImport.Create(uploadFile);
                ViewBag.Ready = true;
            }
            else
                RedirectToAction("index");
            return View(model);
#else
            return RedirectToRoute("Default");
#endif
        }

        [HttpPost]
        public ActionResult Import(string id, FormCollection formData)
        {
#if DEBUG
            var uploadedFile = RavenSession.Load<Models.UploadedFile>(id);
            var model = ViewModels.FileManagerImport.Create(uploadedFile);

            if (!string.IsNullOrEmpty(formData["BeginImport"]))
            {
                int i = 0;
                var stopWatch = System.Diagnostics.Stopwatch.StartNew();
                foreach (var item in model.ReadRowData(uploadedFile.FullPath))
                {
                    switch (model.Category.ToLower())
                    {
                        case "quakers":
                            var quaker = Models.Quaker.Create(item, uploadedFile.Id);
                            if (quaker != null)
                            {
                                RavenSession.Store(quaker);
                                i++;
                            }
                            break;
                        case "ministers":
                            var minister = Models.Minister.Create(item, uploadedFile.Id);
                            if (minister != null)
                            {
                                RavenSession.Store(minister);
                                i++;
                            }
                            break;
                        default:
                            break;
                    }
                }
                stopWatch.Stop();
                uploadedFile.ImportedAt = DateTime.Now;
                uploadedFile.NumberOfRecords = i;

                TempData.Add("RecordsAdded", i);
                TempData.Add("ImportTimeSpan", stopWatch.Elapsed);
            }
            else
            {
                model.ReadHeaders();
                return View(model);
            }
            return RedirectToAction("index");
#else
            return RedirectToRoute("Default");
#endif
        }


        public static string UndoImportLinkPath = "/filemanager/undoimport/";
        [HttpGet]
        public ActionResult UndoImport(string id)
        {
            ViewModels.FileManagerUndoImport model;
            if (string.IsNullOrEmpty(id))
                return RedirectToAction("index");

            var uploadedFile = RavenSession.Load<Models.UploadedFile>(id);
            model = ViewModels.FileManagerUndoImport.Create(uploadedFile.Id);
            model.RemainingRecords = RavenSession.Query<Models.Quaker>().Count();

            return View(model);
        }

        [HttpPost]
        public ActionResult UndoImport(ViewModels.FileManagerUndoImport model)
        {
            if (!model.ConfirmRemoval)
            {
                return View(model);
            }

            var stopWatch = System.Diagnostics.Stopwatch.StartNew();

            var recordsToDelete = RavenSession.Query<Models.Quaker>().Where(q => q.UploadedFileId == model.UploadedFileId)
                .Take(model.BatchSize);

            int numberOfRecordsToDelete = recordsToDelete.Count();
            if (numberOfRecordsToDelete == 0)
            {
                var uploadedFile = RavenSession.Load<Models.UploadedFile>(model.UploadedFileId);
                uploadedFile.ImportedAt = null;
                uploadedFile.NumberOfRecords = null;

                model.RemainingRecords = 0;
                model.ConfirmRemoval = false;
                return RedirectToAction("index");
                //return View(model);
            }
            foreach (var record in recordsToDelete)
            {
                RavenSession.Delete<Models.Quaker>(record);
            }

            if (model.BatchSize <= model.RemainingRecords)
                model.RemainingRecords = model.RemainingRecords - model.BatchSize;
            else
                model.RemainingRecords = 0;


            if (model.RemainingRecords == 0)
            {
                var uploadedFile = RavenSession.Load<Models.UploadedFile>(model.UploadedFileId);
                uploadedFile.ImportedAt = null;
                uploadedFile.NumberOfRecords = null;

                model.ConfirmRemoval = false;
            }
            stopWatch.Stop();

            model.ExecutionTimeSpan = stopWatch.Elapsed;

            ViewBag.SuccessMessage = string.Format("Remaining records {0}... ", numberOfRecordsToDelete);
            ViewBag.DisbalePageTracking = true;
            return View(model);
        }

    }
}

Tombstones.UI.Web/Tombstones.UI.Web/Views/FileManager/Import.cshtml
@model Tombstones.UI.Web.ViewModels.FileManagerImport
@{
    ViewBag.Title = "Import";
}

<h2>Import</h2>

@*<form action="@string.Format(@"{0}/{1}",
 Tombstones.UI.Web.Controllers.FileManagerController.ImportLinkPath, Model.UploadFileId)" method="post">
*@

@using(Html.BeginForm("Import", "FileManager", FormMethod.Post))
{

<h3>File Headers</h3>
<table>
    <thead>
        <tr>
            @foreach (var header in Model.Headers)
            {
                <th>@header</th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var row in Model.SampleData)
        {
            <tr>
                @foreach (var item in row)
                {
                    <td>@item</td>
		 
                }
            </tr>
        }
    </tbody>
</table>
<br />

    
<input type="checkbox" name="BeginImport" value="BeginImport" id="importCheckBox" /><label for="importCheckBox">I want to start the import.</label>
    <input type="submit" name="Import" value="Import" />
@*</form>*@

}

Tombstones.UI.Web/Tombstones.UI.Web/Views/FileManager/Index.cshtml
@model Tombstones.UI.Web.ViewModels.FileManagerIndex
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                @if (ViewBag.SubTitle != null)
                {
                    <h2>@ViewBag.SubTitle</h2>
                }
            </hgroup>

            @if (ViewBag.NewFile != null)
            {
                <text>The file that you just uploaded.</text>
                var newFile = (Tombstones.UI.Web.Models.UploadedFile)ViewBag.NewFile;
                <span>@newFile.FileName</span><br />
                <span>@newFile.FullPath</span>
            }
        </div>
    </section>

}

<div class="content-wrapper">
    <h3>Files that can be Imported.</h3>
    @if (Model.FilesInUploadFolder != null && Model.FilesInUploadFolder.Count() > 0)
    {
        foreach (var file in Model.FilesInUploadFolder)
        {
        <div class="roundedbox">
            <span class="width200 block">@file.Name</span><span class="width80 block">@file.Length</span>
        </div>
        }
    }
    <hr />
    <span>Files from DB</span><br />
    @if (Model.UploadedFiles != null && Model.UploadedFiles.Count() > 0)
    {
        <table>
            <thead>
                <tr>
                    <th>Filename</th>
                    <th>Uploaded on</th>
                    <th>Imported on</th>
                    <th></th>
                </tr>
            </thead>
            @foreach (var uploaded in Model.UploadedFiles)
            {
                <tr>
                    <td>@uploaded.FileName</td>
                    <td>@uploaded.UploadedAt.ToString()</td>
                    <td>
                        @if (uploaded.ImportedAt.HasValue)
                        {
                            @uploaded.ImportedAt.Value.ToString();
                        }
                        else
                        {
                            if (@Model.FilesInUploadFolder.Count(f => f.Name == @uploaded.FileName) == 1)
                            {
                            <a href="/filemanager/import/@uploaded.Id">Import now</a>
                            }
                            else
                            {
                            <span title="This file is no longer stored on the server and cannot be imported to the database">can't import</span>
                            }
                        }
                    </td>
                    <td>
                        @if (uploaded.ImportedAt.HasValue)
                        {
                            var url = string.Format("{0}{1}", Tombstones.UI.Web.Controllers.FileManagerController.UndoImportLinkPath,
                                uploaded.Id);
                            <a href="@url" title="Remove all records from this file.">Undo Import</a>
                        }
                    </td>
                </tr>
            }
        </table>
    }
</div>

<aside>
    <ul>
        <li><a href="@Tombstones.UI.Web.Controllers.FileManagerController.UploadLinkPath">Upload</a></li>
    </ul>
</aside>

Tombstones.UI.Web/Tombstones.UI.Web/Views/FileManager/UndoImport.cshtml
@model Tombstones.UI.Web.ViewModels.FileManagerUndoImport
@{
    ViewBag.Title = "UndoImport";
}

<h2>UndoImport</h2>


@using (@Html.BeginForm("UndoImport", "FileManager", FormMethod.Post, new { id = "undoImportForm" }))
{
    @Html.HiddenFor(m => m.UploadedFileId);
    @Html.HiddenFor(m => m.RemainingRecords);
    
    <span class="label width100">Batch Size:</span>
    <span>@Html.TextBoxFor(m => m.BatchSize)</span><br />

    <span class="label width100">Confirm Delete action.</span>
    <span>@Html.CheckBoxFor(m => m.ConfirmRemoval)</span>
    <br />
    <input type="submit" id="undoImportSubmit" name="undoImport" value="Undo Import" />
    
    <br />
}
@section scripts
{
    @if (Model.RemainingRecords != 0)
    {
        <script type="text/javascript">
            $().ready(function undoImportReady() {

                var form = $("#undoImportForm");
                var confirmRemoval = $("#ConfirmRemoval");

                if (confirmRemoval[0].checked) {
                    $("#undoImportSubmit").addClass("disabled");
                    var timeoutId;
                    //timeoutId = setTimeout(function () { form.submit(); clearTimeout(timeoutId); }, 1000);
                    form.submit();
                }
            });

        </script>
    }
}

Tombstones.UI.Web/Tombstones.UI.Web/Views/FileManager/Upload.cshtml
@model Tombstones.UI.Web.ViewModels.FileUpload

@{
    ViewBag.Title = "Upload";
}

<h2>Upload</h2>


<form action="@Tombstones.UI.Web.Controllers.FileManagerController.UploadLinkPath" method="post" enctype="multipart/form-data">
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>FileUpload</legend>
        <span class="editor-label">File to upload: </span>
        <input type="file" name="uploadedFile" id="uploadedFIle" />
        
        <br />
        <span class="editor-label">Category</span>
        @Html.DropDownListFor(m => m.SelectedFileCategory, Model.FileCategories)
        <p>
            <input type="submit" value="Upload" />
        </p>
    </fieldset>
</form>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}